FROM getgauge-python

RUN mkdir -p /tmp/scripts
WORKDIR /tmp
COPY src/scripts ./scripts/

RUN mkdir ~/.pip
RUN mv scripts/host/pip.aliyun.conf ~/.pip/pip.conf
RUN if [ -f scripts/dev/requirements.txt ]; then pip3 install -r scripts/dev/requirements.txt; fi
RUN if [ -f scripts/base/requirements.txt ]; then pip3 install -r scripts/base/requirements.txt; fi
RUN if [ -f scripts/host/requirements.txt ]; then pip3 install -r scripts/host/requirements.txt; fi
RUN rm -rf scripts
RUN echo "done"

