version: '3'
services:
  projcode:
    image: projcode
    restart: always
    volumes:
      - ./conf:/usr/service/src/proj/environ
      - ./conf:/usr/service/conf
      - ./log:/usr/service/log
      - ./web:/usr/service/web
      - ./db:/usr/service/src/db
    env_file:
      - ./.projrc
    ports:
      - 8100:8000 # 容器内统一使用 8000 端口，容器外使用使用项目对应的端口
    # run as http
    command: python manage.py runserver 0.0.0.0:8000
    # OR as uwsgi
    # command: uwsgi --ini /usr/service/conf/uwsgi.ini
  # nginx:
  #   image: nginx
  #   depends_on:
  #     - projcode
  #   restart: always
  #   volumes:
  #     - ./conf/nginx:/etc/nginx/conf.d
  #     - ./log:/usr/service/log
  #     - ./web:/usr/service/web
  #   links:
  #     - projcode
  #   ports:
  #     - 80:80
