version: '3'
services:
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306

  web:
    image: sample
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      DB_URI: "mysql://root:example@mysql/db_test_sample"
    ports:
      - 8000
